##Variables
ajective = input("Adjective: ")
adjective1 = input("Adjective: ")
tob = input("Type of bird: ")
romh = input("Room in the house: ")
verbp2 = input("Verb in past tense: ")
verb = input("Verb: ")
rn = input("Relative name: ")
noun = input("noun: ")
l = input("A liquid: ")
verbing = input("verb ending with -ing: ")
potb = input("Part of the body(plural): ")
pnoun = input("Plural noun: ")
verb1= input("Verb ending with-ing: ")
no = input("Noun: ")

#layout value
print("It was a",ajective,", cold November day.")
print("I woke up to the", adjective1,"smell of",tob,"roasting in the",romh,"downstairs.")
print("I",verbp2,"down the stairs to see if I coluld help",verb,"the dinner.")
print("My mom said see if",rn,"needs a fresh",noun,".")
print("So i carried a tray of glasses full of",l,"into the",verbing,"room")
print("When i got there i couldn't believe my",potb,"!")
print("There were", pnoun , verb1,"on the",no)